### ISSUE TITLE
A few Suggestions

### ISSUE THREAD

**Issue by d00mfish** [LapisPlugins/AFKPlus#10]
Hey, first of all: Great Work! Your Plugin really stands out from the others and we already really like it.  We just switched from our outdated self programmed afk plugin to yours and now I have some things we would definetly consider as improvements:

We would really appreciate a feature where you can set afk kick time for every individual rank or player. (Although player, vip and admin permission already do that kinda. Maybe it would be good to write the permissions somewhere on the spigot page because I didn't find them anywhere. But maybe I was really blind, in that case my apologies.)

Also maybe a config setting so that afk players get god mode and can't be hurt by mobs and other players.

Currently there is the problem that if you want to detect moving for afk, every player can 'bump' others out of the afk status, so we have to disable the moving detection. Now they can run around in AFK mode without it being automatically disabled.
Is it possible to seperate moving from looking or even jumping? Or make players incapable to move when afk so they have to jump once to get out of it?

Of  course you don't have to do anything we suggest but we and I think other users as well would really aprecciate some of the features.
It would be great to hear your opinion about this.

So long, Leo

**Comment by Dart2112** [comment]
You can set individual times for each rank. The permissions in the config are just a sample, you can add your own permissions by using the same format with a different name, so you could rename vip to rank1 and then copy and paste it and have rank2.
as an example `Permissions:
  afkplus,player:
    Default: 1
    Priority: 1
    AFKSelf: 1
    AFKOthers: 0
    TimeToAFK: 30
    TimeToWarning: 90
    TimeToAction: 120
    CanUpdate: 0
  afkplus,rank1:
    Default: 0
    Priority: 2
    AFKSelf: 1
    AFKOthers: 0
    TimeToAFK: 60
    TimeToWarning: 120
    TimeToAction: 150
    CanUpdate: 0
  afkplus,rank2:
    Default: 0
    Priority: 3
    AFKSelf: 1
    AFKOthers: 0
    TimeToAFK: 80
    TimeToWarning: 120
    TimeToAction: 150
    CanUpdate: 0
  afkplus,admin:
    Default: 2
    Priority: 4
    AFKSelf: 1
    AFKOthers: 1
    TimeToAFK: 90
    TimeToWarning: -1
    TimeToAction: -1
    CanUpdate: 1`
This is a valid permsissions setup for AFKPlus where you can change the way that each rank gets handled, just make sure that the higher ranks have a higher priority. 

I can definitely see the advantage of having a "no damage" mode for when players are AFK, I'll look at adding that soon.

The bumping issue is only fixable by using the team features build into Minecraft, some people use scoreboards on their servers that cannot work with teams. This is why this "no bumping" feature is present in the AFKPlus Prefix add-on since this plugin already uses teams to provide the prefix.

I will also split moving and looking into separate detections.

I like to use issues to track things I am adding so here is the list of things I'll be working on:

- Making the permissions system clearer on all plugin pages (since this same permission system is used across many of my plugins) and perhaps include an example of what you can do with it (This will probably be done with a GitHub wiki page on LapisCore and a link on each plugin page)
- Adding an invulnerable state to AFK with a config option to enable
- Advertise the "bump" support provided by the AFKPlusPrefix plugin
- Split looking and moving detections

**Comment by d00mfish** [comment]
Wow thank you so much! It is great to see that you look into improving your plugins and value our feedback.
We now configured the plugin with multiple ranks and are very happy with it. Unfortunately we can't use the prefix plugin because of the problem you described: We already use scoreboards and teams.

I just wrote with an other server admin and he suggested a similiar behaviour to the essentials afk to fix the bump problem:
You get teleported back to your afk coords if sombody or something tries to move you. You get only out of afk by jumping or typing /afk. Looking and Moving won't revoke the afk status, you just get teleported back to the original position and orientation.

Maybe this could be an aproach.

**Comment by Dart2112** [comment]
It should be able to simply ignore movement and teleport you back. Being bumped shouldn't effect rotation. I'll give it a shot and if it works well, I'll add it as another option.

**Comment by d00mfish** [comment]
Your the man! / woman!
Thanks for giving it a shot.

**Comment by Dart2112** [comment]
just a heads up that I am coming into the end of the university semester so it may take a few weeks to do

**Comment by Dart2112** [comment]
Just added most of the code to complete this, you can download and compile it yourself if you wish to test it.
So far I have the bump protection and player damage protection working and tested, I haven't tested the other damage option.
I should be able to test it properly and push out the update in the next few days.

**Comment by d00mfish** [comment]
Wow that was veery fast! I'll compile it tomorrow and test it. Of course uni comes first, I also have a lot going on this semester so I totally understand you ;) But you do great work, so take your time!
