### ISSUE TITLE
Advanced settings / description for AggressiveAFKDetection

### ISSUE THREAD

**Issue by RedstoneFuture** [LapisPlugins/AFKPlus#62]
Most of the config settings are described in great detail. But the `AggressiveAFKDetection` setting does not explain exactly what the plugin does and does not allow anything to be configured in detail. A comparison with `MovementMagnitude` is therefore difficult.

```
#Enabling aggressive AFK detection will tighten tolerances on AFK machines but may slow down the reaction time of
#removing players from AFK and may also mark players as AFK when they are simply not moving much, this should only
#be enabled if you are having trouble with players using machines like AFK fishing farms
AggressiveAFKDetection: false
```

Advanced explanations of behaviors or advanced settings can help here.

**Comment by Dart2112** [comment]
Fair enough. It was kind of vague as the way it works has changed a lot over time and I wasn't sure how it would end up working. But it has now settled into a method so I can write accurate and detailed documentation for that now.
I have made a small change to the way it works which now aligns with the following description

"Aggressive AFK Detection is an attempt to stop people from using AFK farms or machines

It does this by checking that players are moving in both look (using the mouse to look around) and transform (using wasd to move)

If a player is only moving in one of these ways they will stop triggering the detections that are enabled in "EnabledDetections"

This will force them into AFK unless they start moving in both look and transform

This can be over-kill and should only be enabled if you know people are attempting to bypass AFKPlus by triggering detections while still being AFK"

I'll be pushing these changes so that they will be included in the next update, but that won't be right away. So if you have any feedback on that wording or anymore questions about how it works, I would appreciate the feedback.

**Comment by RedstoneFuture** [comment]
Ah okay, thanks.

> If a player is only moving in one of these ways they will stop triggering the detections that are enabled in "EnabledDetections"

This is somewhat contradictory to the `EnabledDetections` setting, as it explicitly only looks at "Look" or "Move". The combination of both is then the actual feature. And it only affects these two options.

**Comment by Dart2112** [comment]
To be clear, no detections work when a player is considered to be "inactive" by aggressive AFK detection, regardless of which detections you have enabled in the config.
They can be typing in chat and clicking all the things, but if they aren't at least moving about a little **and** looking a little they will be marked "inactive". This does make it **very** aggressive hence the warning to only use it if it's needed because it will lead to false positives in terms of setting players as AFK. it also means that when a player tries to leave AFK by moving they will need to move and look and then also wait for aggressive AFK detection to run and notice that they are looking and moving again. Then and only then does it remove them from AFK.

It's included for servers with AFK farm/machine issues who are willing to deal with the false positives for the sake of kicking players trying to bypass AFK detection.

**Comment by RedstoneFuture** [comment]
Ah, I understand. Thanks for the clarification. :)

**Comment by Dart2112** [comment]
An update has been pushed out so this is now live. Thanks for helping improve AFKPlus
